spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## service1
        - id: authentification_microservice
          uri: lb://authentification_microservice
          predicates:
            - Path=/authentification_microservice/**
          filters:
            - StripPrefix=1

        ## Service2
        - id: reservation_microservice
          uri: lb://reservation_microservice
          predicates:
            - Path=/reservation_microservice/**
          filters:
            - StripPrefix=1

        ## Service3
        - id: profile_microservice
          uri: lb://profile_microservice
          predicates:
            - Path=/profile_microservice/**
          filters:
            - StripPrefix=1
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka